const DATA = [
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Average",
  "planning": "Often",
  "balance": "Often",
  "challenge": "Procrastination",
  "postpone": "Often",
  "mobile": "3–5 hours",
  "assign_diff": "Sometimes",
  "perf_impact": "Agree",
  "stress": "Often",
  "method": "Mobile reminders",
  "improve": "Better planning",
  "reason": "Procrastination"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Average",
  "planning": "Sometimes",
  "balance": "Sometimes",
  "challenge": "Social media",
  "postpone": "Sometimes",
  "mobile": "Less than 1 hour",
  "assign_diff": "Sometimes",
  "perf_impact": "Agree",
  "stress": "Often",
  "method": "To-do list",
  "improve": "Setting priorities",
  "reason": "Lack of proper planning"
 },
 {
  "gender": "Male",
  "age": "17–19",
  "year": "3rd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Good",
  "planning": "Often",
  "balance": "Sometimes",
  "challenge": "Academic work",
  "postpone": "Often",
  "mobile": "3–5 hours",
  "assign_diff": "Sometimes",
  "perf_impact": "Agree",
  "stress": "Never",
  "method": "No method",
  "improve": "Reduced social media usage",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Male",
  "age": "17–19",
  "year": "2nd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Poor",
  "planning": "Often",
  "balance": "Always",
  "challenge": "Academic work",
  "postpone": "Often",
  "mobile": "Less than 1 hour",
  "assign_diff": "Always",
  "perf_impact": "Strongly disagree",
  "stress": "Often",
  "method": "Calendar",
  "improve": "Reduced social media usage",
  "reason": "Too much academic work"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "4th year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Good",
  "planning": "Sometimes",
  "balance": "Always",
  "challenge": "Social media",
  "postpone": "Often",
  "mobile": "Less than 1 hour",
  "assign_diff": "Often",
  "perf_impact": "Disagree",
  "stress": "Always",
  "method": "No method",
  "improve": "Reduced social media usage",
  "reason": "Procrastination"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "4th year",
  "study_hours": "2–4 hours",
  "tm_rating": "Average",
  "planning": "Always",
  "balance": "Often",
  "challenge": "Social media",
  "postpone": "Sometimes",
  "mobile": "1–3 hours",
  "assign_diff": "Always",
  "perf_impact": "Disagree",
  "stress": "Never",
  "method": "No method",
  "improve": "Time management training",
  "reason": "Too much academic work"
 },
 {
  "gender": "Male",
  "age": "17–19",
  "year": "1st year",
  "study_hours": "4–6 hours",
  "tm_rating": "Poor",
  "planning": "Never",
  "balance": "Always",
  "challenge": "Lack of planning",
  "postpone": "Always",
  "mobile": "More than 5 hours",
  "assign_diff": "Always",
  "perf_impact": "Disagree",
  "stress": "Often",
  "method": "To-do list",
  "improve": "Reduced social media usage",
  "reason": "Procrastination"
 },
 {
  "gender": "Male",
  "age": "17–19",
  "year": "3rd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Good",
  "planning": "Sometimes",
  "balance": "Often",
  "challenge": "Lack of planning",
  "postpone": "Often",
  "mobile": "More than 5 hours",
  "assign_diff": "Never",
  "perf_impact": "Agree",
  "stress": "Always",
  "method": "To-do list",
  "improve": "Better planning",
  "reason": "Too much academic work"
 },
 {
  "gender": "Male",
  "age": "23–25",
  "year": "2nd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Average",
  "planning": "Never",
  "balance": "Often",
  "challenge": "Academic work",
  "postpone": "Often",
  "mobile": "Less than 1 hour",
  "assign_diff": "Often",
  "perf_impact": "Disagree",
  "stress": "Never",
  "method": "Mobile reminders",
  "improve": "Reduced social media usage",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Female",
  "age": "23–25",
  "year": "2nd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Poor",
  "planning": "Always",
  "balance": "Always",
  "challenge": "Social media",
  "postpone": "Often",
  "mobile": "1–3 hours",
  "assign_diff": "Always",
  "perf_impact": "Disagree",
  "stress": "Never",
  "method": "To-do list",
  "improve": "Better planning",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "Less than 2 hours",
  "tm_rating": "Excellent",
  "planning": "Always",
  "balance": "Often",
  "challenge": "Social media",
  "postpone": "Always",
  "mobile": "1–3 hours",
  "assign_diff": "Always",
  "perf_impact": "Disagree",
  "stress": "Always",
  "method": "To-do list",
  "improve": "Reduced social media usage",
  "reason": "Too much academic work"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Good",
  "planning": "Always",
  "balance": "Often",
  "challenge": "Social media",
  "postpone": "Often",
  "mobile": "1–3 hours",
  "assign_diff": "Always",
  "perf_impact": "Agree",
  "stress": "Never",
  "method": "Calendar",
  "improve": "Time management training",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Female",
  "age": "23–25",
  "year": "3rd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Good",
  "planning": "Never",
  "balance": "Always",
  "challenge": "Lack of planning",
  "postpone": "Often",
  "mobile": "3–5 hours",
  "assign_diff": "Always",
  "perf_impact": "Disagree",
  "stress": "Often",
  "method": "No method",
  "improve": "Time management training",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "4–6 hours",
  "tm_rating": "Excellent",
  "planning": "Often",
  "balance": "Often",
  "challenge": "Social media",
  "postpone": "Sometimes",
  "mobile": "1–3 hours",
  "assign_diff": "Often",
  "perf_impact": "Strongly agree",
  "stress": "Always",
  "method": "To-do list",
  "improve": "Reduced social media usage",
  "reason": "Too much academic work"
 },
 {
  "gender": "Female",
  "age": "17–19",
  "year": "2nd year",
  "study_hours": "4–6 hours",
  "tm_rating": "Good",
  "planning": "Often",
  "balance": "Always",
  "challenge": "Social media",
  "postpone": "Sometimes",
  "mobile": "3–5 hours",
  "assign_diff": "Never",
  "perf_impact": "Disagree",
  "stress": "Never",
  "method": "To-do list",
  "improve": "Time management training",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "4th year",
  "study_hours": "2–4 hours",
  "tm_rating": "Good",
  "planning": "Never",
  "balance": "Sometimes",
  "challenge": "Academic work",
  "postpone": "Always",
  "mobile": "1–3 hours",
  "assign_diff": "Sometimes",
  "perf_impact": "Strongly agree",
  "stress": "Never",
  "method": "No method",
  "improve": "Better planning",
  "reason": "Excessive mobile use"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "4–6 hours",
  "tm_rating": "Poor",
  "planning": "Never",
  "balance": "Never",
  "challenge": "Lack of planning",
  "postpone": "Always",
  "mobile": "1–3 hours",
  "assign_diff": "Always",
  "perf_impact": "Strongly agree",
  "stress": "Always",
  "method": "Calendar",
  "improve": "Reduced social media usage",
  "reason": "Too much academic work"
 },
 {
  "gender": "Male",
  "age": "23–25",
  "year": "3rd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Average",
  "planning": "Often",
  "balance": "Always",
  "challenge": "Procrastination",
  "postpone": "Sometimes",
  "mobile": "1–3 hours",
  "assign_diff": "Never",
  "perf_impact": "Disagree",
  "stress": "Never",
  "method": "Mobile reminders",
  "improve": "Better planning",
  "reason": "Procrastination"
 },
 {
  "gender": "Male",
  "age": "20–22",
  "year": "3rd year",
  "study_hours": "2–4 hours",
  "tm_rating": "Average",
  "planning": "Often",
  "balance": "Always",
  "challenge": "Social media",
  "postpone": "Never",
  "mobile": "3–5 hours",
  "assign_diff": "Sometimes",
  "perf_impact": "Agree",
  "stress": "Sometimes",
  "method": "Calendar",
  "improve": "Better planning",
  "reason": "Too much academic work"
 }
];
